# Site settings
title: tim geaney
email: timfgeaney@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Freelance web designer and developer, specialising in Jekyll, HTML, CSS and Javascript
baseurl: "/timgeaney-blog" # the subpath of your site, e.g. /blog/
url: "http://example.com" # the base hostname & protocol for your site

twitter_username: timfgeaney
github_username:  timfgeaney
google_username: timfgeaney

permalink: /:categories/:title
links:
    - title: about
      url: /about
    - title: work
      url: /work
    - title: articles
      url: /articles
    - title: hire me
      url: /hire-me

# Build settings
markdown: kramdown